# Generated by Django 3.1.8 on 2021-11-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regions_name', models.CharField(max_length=100)),
                ('regions_ref', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenants_name', models.CharField(max_length=100)),
                ('tenants_ref', models.CharField(max_length=100)),
            ],
        ),
    ]
