# Generated by Django 3.1.8 on 2021-11-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameSpaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespaces_name', models.CharField(max_length=100)),
                ('namespaces_ref', models.CharField(max_length=100)),
            ],
        ),
    ]
